[package]
name = "robrowser-remoteclient"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
clap = { version = "4.6.6", features = ["derive", "env"] }
encoding_rs = "0.8.35"
flate2 = "1.1.9"
memmap2 = "0.9.11"
percent-encoding = "2.3.2"
regex = "1.13.1"
tokio = { version = "1.53.1", features = [
  "rt-multi-thread",
  "macros",
  "net",
  "signal",
] }
tower-http = { version = "0.7.0", features = ["cors"] }

[profile.release]
debug = true
